// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderHub.Domain;

public partial class Order
{
    public int Id { get; set; }

    public int SchoolId { get; set; }

    public DateOnly OrderDate { get; set; }

    public string Season { get; set; }

    public decimal Total { get; set; }

    public string Status { get; set; }

    public virtual School School { get; set; }
}