// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderHub.Domain;

public partial class Product
{
    public int Id { get; set; }

    public string Sku { get; set; }

    public decimal BasePrice { get; set; }

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();

    public virtual Stock Stock { get; set; }
}