// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderHub.Domain;

public partial class School
{
    public int Id { get; set; }

    public string TierCode { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}