// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderHub.Domain;

public partial class Stock
{
    public int Id { get; set; }

    public string Sku { get; set; }

    public int Qty { get; set; }

    public virtual Product SkuNavigation { get; set; }
}